### ISSUE TITLE
tag a release for packagist

### ISSUE THREAD

**Issue by gordalina** [adoy/PHP-FastCGI-Client#9]
Could you guys tag a version for packagist.
I'm using this library in [cachetool](https://github.com/gordalina/cachetool) and it sucks that i have to set the `minimum-stability` to `dev`

**Comment by Timandes** [comment]
:+1:

**Comment by gordalina** [comment]
ping @remicollet

**Comment by adoy** [comment]
Hi,

I just tagged 1.0.0

**Comment by gordalina** [comment]
thanks @adoy
